### GET request to example server
POST http://34.53.35.1:8000/infer
Content-Type: application/json

{
  "prompt": "안녕?",
  "max_length": 150
}

### POST ASK
POST http://34.53.35.1:8000/ask
Content-Type: application/json

{
  "question": "일본의 수도는?",
  "max_length": 1500
}
