### GET request to example server
POST http://34.53.35.1:8000/infer
Content-Type: application/json

{
  "prompt": "안녕?",
  "max_length": 150
}

### POST ASK
POST http://34.53.35.1:8000/ask
Content-Type: application/json

{
  "question": "머리를 자르면 새로운 머리가 두 개 자라나는 뱀 괴물은 무엇일까요?",
  "max_length": 1500
}
